### ISSUE TITLE
Zoom image map 

### ISSUE THREAD

**Issue by Khmertracks** [naver/ImageMaps#3]
i want you develop zoom function like link below.
http://www.htmldrive.net/items/demo/394/JQuery.iviewer-zoom-image-and-to-drag-effect
it easy to zoom and scroll .
hope you can do it.. :+1:

**Comment by ahnbj2000** [comment]
mouse zoom function is not appropriate to provide in the plugin.
It is recommended to direct implementation in the service code.

``
example>
$ (ImageElement) .on ( 'mousewheel', function (event) {
    ...
});
``

**Comment by songkhmer** [comment]
OK thank you 😃
But you don't forget fix text when move
