### ISSUE TITLE
Modernizing

### ISSUE THREAD

**Issue by brettz9** [naver/ImageMaps#6]
There are a number enhancements I'd like to add to your awesome tool and was hoping I could get feedback on whether you are still maintaining the repository, and if so, what your opinions were on the following:

1. Publishing to npm. I'd do it under your npm user name and repo if you wanted to do publishing. Otherwise, I might just publish my own fork.
2. Adding ESLint. I'm partial to my own rather strict standards at https://github.com/brettz9/eslint-config-ash-nazg , but I could apply a different set if you preferred.
3. Converting to ES6 Modules and ES6 source, using Rollup and Babel for distribution files (both UMD and ES bundles), ideally, imo, in a `src` and `dist` directory.
4. ~Possibly avoiding the jQuery dependency by~ using ES6 and modern browser features (which can be polyfilled for those targeting older browsers).
5. Though I'm not keen to add a bunch of tests now, I thought it might be nice to add the awesome [testcafe](https://github.com/DevExpress/testcafe) for UI tests so tests can be added as contributors may be inspired.
6. Add JSDoc

Besides getting your feedback, I'd really hope you might be willing to apply your genius to complete the unfinished polyline feature as it would be really great to have this fundamental type of map added to the available options.

Thanks very much!

**Comment by brettz9** [comment]
If you are no longer maintaining, please let me know, so I can release my own updated version of your package.

**Comment by todtod80** [comment]
@brettz9 
Good job. Please take a moment to review. /cc @ahnbj2000

**Comment by ahnbj2000** [comment]
@brettz9 
I will check PR. And publishing to npm is a good idea, i will proceed. thanks.

**Comment by brettz9** [comment]
By the way, to possibly save some of your time, feel free to ask why any changes were made...

**Comment by ahnbj2000** [comment]
@brettz9 
I published it in npm. I will complement the readme and demo.

**Comment by brettz9** [comment]
Wonderful... Btw, you may want to update `gh-pages`, since now this fork includes an updated, improved version of the demo that `gh-pages` has.

Also, my personal suggestion would be to make tags in the form `v1.0.0` (instead of just `v1`) even for new major releases, so people know more clearly that you are using "semantic versioning" and so they can find the tag predictably, since other projects I think tend to use the fuller form for tags than just `v1`.

And thank you all again for an excellent code base. I'm eager to try to put it to good use!
